site_name: deferral
repo_url: https://github.com/claudiubelu/deferral
site_url: https://claudiubelu.github.io/deferral
site_description: Python's missing defer. Cleanup code where it belongs — next to the resource that needs cleaning up.
site_author: Claudiu Belu
edit_uri: edit/main/docs/
repo_name: claudiubelu/deferral
copyright: Maintained by <a href="https://claudiubelu.com">claudiubelu</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["deferral"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/claudiubelu/deferral
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/deferral

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
